import type { NextPage } from 'next'
import Head from 'next/head'
import { NavBar } from '../src/components/index'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
            rel="preload"
            href="/assets/Dongle-Regular.ttf"
            as="font"
            crossOrigin=""
          />
          <link
            rel="preload"
            href="/assets/Dongle-Bold.ttf"
            as="font"
            crossOrigin=""
          />
      </Head>
      <main className={styles.main}>
        
      </main>
    </div>
  )
}

export default Home
