import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useMessageError } from '../src/store/messageStore';

const Home: NextPage = () => {

  const setError = useMessageError( state => state.setError )

  const click = () => {
    setError({
      error   : true,
      message : 'Error message',
      type    : 'error'
    })
  }
  
  return (
    <div >
      <Head>
        <title>Elefante blanco</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
            rel=""
            href="/assets/Dongle-Regular.ttf"
            as="font"
            crossOrigin="anonymous"
          />
          <link
            rel="prefetch"
            href="/assets/Dongle-Bold.ttf"
            as="font"
            crossOrigin="anonymous"
          />
      </Head>
      <main className={styles.main}>
        <h1>
          Ciudemos lo que es de nosotros, ayuda a construir un mejor país.
        </h1>
        <p>
          Elefante blanco es una plataforma que permite a los ciudadanos
          registrar actos de corrupción.
        </p>

        <button onClick={click} >Message</button>

      </main>
    </div>
  )
}

export default Home
